- name: Setup environment
  hosts: localhost
  connection: local

  tags:
    - install
    - configure

  vars:
    go_version: 1.20.3
    go_archive: "go{{ go_version }}.{{ 'darwin-amd64' if ansible_os_family == 'Darwin' else 'linux-amd64' if ansible_os_family == 'Debian' }}.tar.gz"
    go_checksum: "{{ 'c1e1161d6d859deb576e6cfabeb40e3d042ceb1c6f444f617c3c9d76269c3565' if ansible_os_family == 'Darwin' else '979694c2c25c735755bf26f4f45e19e64e4811d661dd07b8c010f7a8e18adfca' if ansible_os_family == 'Debian' }}"

  pre_tasks:
  - import_tasks: tasks/ubuntu/prepare.yml
    when: ansible_os_family == 'Debian'
  - import_tasks: tasks/macOS/prepare.yml
    when: ansible_os_family == 'Darwin'


  tasks:
  - import_tasks: tasks/ubuntu/essentials.yml
    when: ansible_os_family == 'Debian'
  - import_tasks: tasks/macOS/essentials.yml
    when: ansible_os_family == 'Darwin'
  - import_tasks: tasks/zsh.yml
  - import_tasks: tasks/vim.yml
  - import_tasks: tasks/go.yml
  - import_tasks: tasks/node.yml
  - import_tasks: tasks/deno.yml
  - import_tasks: tasks/dotfiles.yml
