- name: Setup environment
  hosts: localhost
  connection: local

  tags:
    - install
    - configure

  vars:
    go_version: 1.20.6
    go_archive: "go{{ go_version }}.{{ 'darwin-amd64' if ansible_os_family == 'Darwin' else 'linux-amd64' if ansible_os_family == 'Debian' }}.tar.gz"
    go_checksum: "{{ '98a09c085b4c385abae7d35b9155195d5e584d14988347ac7f18e4cbe3b5ef3d' if ansible_os_family == 'Darwin' else 'b945ae2bb5db01a0fb4786afde64e6fbab50b67f6fa0eb6cfa4924f16a7ff1eb' if ansible_os_family == 'Debian' }}"

  pre_tasks:
  - import_tasks: tasks/ubuntu/prepare.yml
    when: ansible_os_family == 'Debian'
  - import_tasks: tasks/macOS/prepare.yml
    when: ansible_os_family == 'Darwin'


  tasks:
  - import_tasks: tasks/ubuntu/essentials.yml
    when: ansible_os_family == 'Debian'
  - import_tasks: tasks/macOS/essentials.yml
    when: ansible_os_family == 'Darwin'
  - import_tasks: tasks/zsh.yml
  - import_tasks: tasks/vim.yml
  - import_tasks: tasks/go.yml
  - import_tasks: tasks/node.yml
  - import_tasks: tasks/deno.yml
  - import_tasks: tasks/dotfiles.yml
