- name: Setup environment
  hosts: localhost
  connection: local

  tags:
    - install
    - configure

  pre_tasks:
  - import_tasks: tasks/ubuntu/prepare.yml
    when: ansible_os_family == 'Debian'
  - import_tasks: tasks/macOS/prepare.yml
    when: ansible_os_family == 'Darwin'


  tasks:
  - import_tasks: tasks/ubuntu/essentials.yml
    when: ansible_os_family == 'Debian'
  - import_tasks: tasks/macOS/essentials.yml
    when: ansible_os_family == 'Darwin'
  - import_tasks: tasks/zsh.yml
  - import_tasks: tasks/vim.yml
  - import_tasks: tasks/ubuntu/go.yml
    when: ansible_os_family == 'Debian'
  - import_tasks: tasks/macOS/go.yml
    when: ansible_os_family == 'Darwin'
  - import_tasks: tasks/node.yml
  - import_tasks: tasks/dotfiles.yml
