- name: Setup environment
  hosts: localhost
  connection: local

  tags:
    - install
    - configure

  vars:
    go_version: 1.24.1
    go_archive: "go{{ go_version }}.{{ 'darwin-amd64' if ansible_os_family == 'Darwin' else 'linux-amd64' if ansible_os_family == 'Debian' }}.tar.gz"
    go_checksum: "{{ '58d529334561cff11087cd4ab18fe0b46d8d5aad88f45c02b9645f847e014512' if ansible_os_family == 'Darwin' else 'cb2396bae64183cdccf81a9a6df0aea3bce9511fc21469fb89a0c00470088073' if ansible_os_family == 'Debian' }}"

  pre_tasks:
    - import_tasks: tasks/ubuntu/prepare.yml
      when: ansible_os_family == 'Debian'
    - import_tasks: tasks/macOS/prepare.yml
      when: ansible_os_family == 'Darwin'

  tasks:
    - import_tasks: tasks/ubuntu/essentials.yml
      when: ansible_os_family == 'Debian'
    - import_tasks: tasks/macOS/essentials.yml
      when: ansible_os_family == 'Darwin'
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/go.yml
    - import_tasks: tasks/volta.yml
    - import_tasks: tasks/bun.yml
    - import_tasks: tasks/dotfiles.yml
