- name: Setup environment
  hosts: localhost
  connection: local

  tags:
    - install
    - configure

  vars:
    go_version: 1.23.4
    go_archive: "go{{ go_version }}.{{ 'darwin-amd64' if ansible_os_family == 'Darwin' else 'linux-amd64' if ansible_os_family == 'Debian' }}.tar.gz"
    go_checksum: "{{ '6700067389a53a1607d30aa8d6e01d198230397029faa0b109e89bc871ab5a0e' if ansible_os_family == 'Darwin' else '6924efde5de86fe277676e929dc9917d466efa02fb934197bc2eba35d5680971' if ansible_os_family == 'Debian' }}"

  pre_tasks:
  - import_tasks: tasks/ubuntu/prepare.yml
    when: ansible_os_family == 'Debian'
  - import_tasks: tasks/macOS/prepare.yml
    when: ansible_os_family == 'Darwin'


  tasks:
  - import_tasks: tasks/ubuntu/essentials.yml
    when: ansible_os_family == 'Debian'
  - import_tasks: tasks/macOS/essentials.yml
    when: ansible_os_family == 'Darwin'
  - import_tasks: tasks/zsh.yml
  - import_tasks: tasks/vim.yml
  - import_tasks: tasks/go.yml
  - import_tasks: tasks/volta.yml
  - import_tasks: tasks/deno.yml
  - import_tasks: tasks/bun.yml
  - import_tasks: tasks/dotfiles.yml
