- name: Setup macOS environment
  hosts: localhost
  connection: local

  pre_tasks:
  - name: Update homebrew
    homebrew:
      update_homebrew: true
      state: present

  tags:
    - install
    - configure

  tasks:
  - name: Install essential macOS packages
    homebrew:
      name: "{{ item }}"
    with_items:
      - stow
      - vim
    tags:
      - install
      - macOS

  - import_tasks: tasks/zsh.yml
  - import_tasks: tasks/vim.yml
  - import_tasks: tasks/go.yml
  - import_tasks: tasks/dotfiles.yml
