- name: Clone dotfiles
  git:
    repo: https://github.com/rshurts/.dotfiles.git
    dest: ~/.dotfiles
  tags:
    - install

- name: Stow dotfiles
  shell: cd ~/.dotfiles && stow git zsh vim jetbrains
  tags:
    - configure
    - git
    - zsh
    - vim
