- name: Install essential linux packages
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - build-essential
    - make
    - curl
    - wget
    - stow
    - git
    - ripgrep
    - zsh
    - vim
  tags:
    - install
    - linux
