- name: Install essential linux packages
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - build-essential
    - curl
    - wget
    - unzip
    - stow
    - git
    - ripgrep
    - fd-find
    - zsh
  tags:
    - install
    - linux
