- name: Download go
  get_url:
    url: https://go.dev/dl/go1.20.linux-amd64.tar.gz
    dest: ~/go1.20.linux-amd64.tar.gz
    checksum: sha256:5a9ebcc65c1cce56e0d2dc616aff4c4cedcfbda8cc6f0288cc08cda3b18dcbf1
  tags:
   - install
   - go

- name: Untar go
  become: true
  unarchive:
    src: ~/go1.20.linux-amd64.tar.gz
    dest: /usr/local
  tags:
    - install
    - go

- name: Cleanup go download
  file:
    path: ~/go1.20.linux-amd64.tar.gz
    state: absent
  tags:
    - install
    - go
