- name: Install essential macOS packages
  homebrew:
    name: "{{ item }}"
  with_items:
    - stow
    - gnu-tar
    - wget
    - ripgrep
    - fd
    - neovim
    - vim
  tags:
    - install
    - macOS
